const CourseData = [
  {
    id: "1",
    name: "Biology",
    department: "I",
    program: "Biology",
    btn_1Link: "xyz1",
    btn_2Link: "abc1",
    btn_3Link: "qwe1",
    btn_4Link: "cvs1",
  },
  {
    id: "2",
    name: "Chemistry",
    department: "II",
    program: "Chemistry",
    btn_1Link: "xyz2",
    btn_2Link: "abc2",
    btn_3Link: "qwe2",
    btn_4Link: "cvs2",
  },
  {
    id: "3",
    name: "English Grammar",
    department: "III",
    program: "English Grammar",
    btn_1Link: "xyz3",
    btn_2Link: "abc3",
    btn_3Link: "qwe3",
    btn_4Link: "cvs3",
  },
  {
    id: "4",
    name: "Mathamatics",
    department: "VIII",
    program: "Mathamatics",
    btn_1Link: "xyz4",
    btn_2Link: "abc4",
    btn_3Link: "qwe4",
    btn_4Link: "cvs4",
  },
  {
    id: "5",
    name: "Physics",
    department: "IV",
    program: "Physics",
    btn_1Link: "xyz5",
    btn_2Link: "abc5",
    btn_3Link: "qwe5",
    btn_4Link: "cvs5",
  },
  {
    id: "6",
    name: "Social Studies",
    department: "IV",
    program: "Social Studies",
    btn_1Link: "xyz67",
    btn_2Link: "abc67",
    btn_3Link: "qwe67",
    btn_4Link: "cvs67",
  },
  {
    id: "7",
    name: "java",
    department: "V",
    program: "java",
    btn_1Link: "xyz7",
    btn_2Link: "abc7",
    btn_3Link: "qwe7",
    btn_4Link: "cvs7",
  },
  {
    id: "8",
    name: "html",
    department: "VI",
    program: "html",
    btn_1Link: "xyz8",
    btn_2Link: "abc8",
    btn_3Link: "qwe8",
    btn_4Link: "cvs8",
  },
  {
    id: "9",
    name: "css",
    department: "VII",
    program: "css",
    btn_1Link: "xyz9",
    btn_2Link: "abc9",
    btn_3Link: "qwe9",
    btn_4Link: "cvs9",
  },
  {
    id: "10",
    name: "react",
    department: "VIII",
    program: "react",
    btn_1Link: "xyz10",
    btn_2Link: "abc10",
    btn_3Link: "qwe10",
    btn_4Link: "cvs10",
  },
  {
    id: "11",
    name: "nextjs",
    department: " III",
    program: "nextjs",
    btn_1Link: "xyz11",
    btn_2Link: "abc11",
    btn_3Link: "qwe11",
    btn_4Link: "cvs11",
  },
  {
    id: "12",
    name: "jquary",
    department: "II",
    program: "jquary",
    btn_1Link: "xyz12",
    btn_2Link: "abc12",
    btn_3Link: "qwe12",
    btn_4Link: "cvs12",
  },
  {
    id: "13",
    name: "c++",
    department: " IX",
    program: "c++",
    btn_1Link: "xyz13",
    btn_2Link: "abc13",
    btn_3Link: "qwe13",
    btn_4Link: "cvs13",
  },
  {
    id: "14",
    name: "flutter",
    department: "X",
    program: "flutter",
    btn_1Link: "xyz14",
    btn_2Link: "abc14",
    btn_3Link: "qwe14",
    btn_4Link: "cvs14",
  },
  {
    id: "15",
    name: "dart",
    department: "VIII",
    program: "dart",
    btn_1Link: "xyz15",
    btn_2Link: "abc15",
    btn_3Link: "qwe15",
    btn_4Link: "cvs15",
  },









  {
    id: "16",
    name: "invints",
    department: "I",
    program: "invints",
    btn_1Link: "xyz14",
    btn_2Link: "abc17",
    btn_3Link: "qwe17",
    btn_4Link: "cvs18",
  },
  {
    id: "17",
    name: "Chemistry++",
    department: "II",
    program: "Chemistry++",
    btn_1Link: "xyz253",
    btn_2Link: "abc2853",
    btn_3Link: "qwe275",
    btn_4Link: "cvs2853",
  },
  {
    id: "18",
    name: "English ",
    department: "III",
    program: "English  ",
    btn_1Link: "xyz375",
    btn_2Link: "abc33",
    btn_3Link: "qwe33",
    btn_4Link: "cvs378",
  },
  {
    id: "19",
    name: "logs",
    department: "VIII",
    program: "logs",
    btn_1Link: "xyz485",
    btn_2Link: "abc43",
    btn_3Link: "qwe43",
    btn_4Link: "cvs43",
  },
  {
    id: "20",
    name: "Physics++",
    department: "IV",
    program: "Physics++",
    btn_1Link: "xyz5",
    btn_2Link: "abc585378",
    btn_3Link: "qwe5738",
    btn_4Link: "cvs578638",
  },
  {
    id: "21",
    name: "Social Studies",
    department: "IV",
    program: "Social Studies",
    btn_1Link: "xyz6773878",
    btn_2Link: "abc683857",
    btn_3Link: "qwe68537",
    btn_4Link: "cvs763867",
  },
  {
    id: "22",
    name: "java++",
    department: "V",
    program: "java++",
    btn_1Link: "x853yz7",
    btn_2Link: "ab7c7",
    btn_3Link: "qw738e7",
    btn_4Link: "cv3s7",
  },
  {
    id: "23",
    name: "html5",
    department: "VI",
    program: "html5",
    btn_1Link: "xy78z8",
    btn_2Link: "ab78c8",
    btn_3Link: "qw7767e8",
    btn_4Link: "cv767s8",
  },
  {
    id: "24",
    name: "ux",
    department: "VII",
    program: "ux",
    btn_1Link: "x76yz9",
    btn_2Link: "a786bc9",
    btn_3Link: "qw76e9",
    btn_4Link: "c8v76s9",
  },
  {
    id: "25",
    name: "ui-ux",
    department: "VIII",
    program: "ui-ux",
    btn_1Link: "xyz7610",
    btn_2Link: "ab786c10",
    btn_3Link: "qw78e10",
    btn_4Link: "cvs7810",
  },
  {
    id: "26",
    name: "xd",
    department: " III",
    program: "xd",
    btn_1Link: "xy786z11",
    btn_2Link: "ab786c11",
    btn_3Link: "qw786e11",
    btn_4Link: "cv5868s11",
  },
  {
    id: "27",
    name: "mern",
    department: "II",
    program: "mern",
    btn_1Link: "xy86z12",
    btn_2Link: "ab786c12",
    btn_3Link: "qw786e12",
    btn_4Link: "cv786s12",
  },
  {
    id: "28",
    name: "c#",
    department: " IX",
    program: "c#",
    btn_1Link: "xy7868z13",
    btn_2Link: "ab76c13",
    btn_3Link: "qw786e13",
    btn_4Link: "cvs78613",
  },
  {
    id: "29",
    name: "geopolitics",
    department: "X",
    program: "geopolitics",
    btn_1Link: "xyz1471",
    btn_2Link: "abc143",
    btn_3Link: "qwe147828",
    btn_4Link: "cvs144",
  },
  {
    id: "30",
    name: "phthon",
    department: "VI",
    program: "phthon",
    btn_1Link: "xyz150",
    btn_2Link: "abc154",
    btn_3Link: "qwe1585",
    btn_4Link: "cvs157",
  },









  {
    id: "31",
    name: "Biology++",
    department: "I",
    program: "Biology++",
    btn_1Link: "xyz1",
    btn_2Link: "abc1",
    btn_3Link: "qwe1",
    btn_4Link: "cvs1",
  },
  {
    id: "32",
    name: "Chemistry++",
    department: "II",
    program: "Chemistry++",
    btn_1Link: "xyz2",
    btn_2Link: "abc2",
    btn_3Link: "qwe2",
    btn_4Link: "cvs2",
  },
  {
    id: "33",
    name: "English Grammar++",
    department: "III",
    program: "English Grammar++",
    btn_1Link: "xyz3",
    btn_2Link: "abc3",
    btn_3Link: "qwe3",
    btn_4Link: "cvs3",
  },
  {
    id: "34",
    name: "Mathamatics++",
    department: "VIII",
    program: "Mathamatics++",
    btn_1Link: "xyz4",
    btn_2Link: "abc4",
    btn_3Link: "qwe4",
    btn_4Link: "cvs4",
  },
  {
    id: "35",
    name: "Physics++",
    department: "IV",
    program: "Physics++",
    btn_1Link: "xyz5",
    btn_2Link: "abc5",
    btn_3Link: "qwe5",
    btn_4Link: "cvs5",
  },
  {
    id: "36",
    name: "Social Studies++",
    department: "IV",
    program: "Social Studies++",
    btn_1Link: "xyz67",
    btn_2Link: "abc67",
    btn_3Link: "qwe67",
    btn_4Link: "cvs67",
  },
  {
    id: "37",
    name: "java++",
    department: "V",
    program: "java++",
    btn_1Link: "xyz7",
    btn_2Link: "abc7",
    btn_3Link: "qwe7",
    btn_4Link: "cvs7",
  },
  {
    id: "38",
    name: "html++",
    department: "VI",
    program: "html++",
    btn_1Link: "xyz8",
    btn_2Link: "abc8",
    btn_3Link: "qwe8",
    btn_4Link: "cvs8",
  },
  {
    id: "39",
    name: "css++",
    department: "VII",
    program: "css++",
    btn_1Link: "xyz9",
    btn_2Link: "abc9",
    btn_3Link: "qwe9",
    btn_4Link: "cvs9",
  },
  {
    id: "40",
    name: "react++",
    department: "VIII",
    program: "react++",
    btn_1Link: "xyz10",
    btn_2Link: "abc10",
    btn_3Link: "qwe10",
    btn_4Link: "cvs10",
  },
  {
    id: "41",
    name: "nextjs++",
    department: " III",
    program: "nextjs++",
    btn_1Link: "xyz11",
    btn_2Link: "abc11",
    btn_3Link: "qwe11",
    btn_4Link: "cvs11",
  },
  {
    id: "42",
    name: "jquary++",
    department: "II",
    program: "jquary++",
    btn_1Link: "xyz12",
    btn_2Link: "abc12",
    btn_3Link: "qwe12",
    btn_4Link: "cvs12",
  },
  {
    id: "43",
    name: "c++++",
    department: " IX",
    program: "c++++",
    btn_1Link: "xyz13",
    btn_2Link: "abc13",
    btn_3Link: "qwe13",
    btn_4Link: "cvs13",
  },
  {
    id: "44",
    name: "flutter++",
    department: "X",
    program: "flutter++",
    btn_1Link: "xyz14",
    btn_2Link: "abc14",
    btn_3Link: "qwe14",
    btn_4Link: "cvs14",
  },
  {
    id: "45",
    name: "dart++",
    department: "VIII",
    program: "dart++",
    btn_1Link: "xyz15",
    btn_2Link: "abc15",
    btn_3Link: "qwe15",
    btn_4Link: "cvs15",
  },








  {
    id: "46",
    name: "invints",
    department: "I",
    program: "invints",
    btn_1Link: "xyz14",
    btn_2Link: "abc17",
    btn_3Link: "qwe17",
    btn_4Link: "cvs18",
  },
  {
    id: "47",
    name: "Chemistry++",
    department: "II",
    program: "Chemistry++",
    btn_1Link: "xyz253",
    btn_2Link: "abc2853",
    btn_3Link: "qwe275",
    btn_4Link: "cvs2853",
  },
  {
    id: "48",
    name: "English ",
    department: "III",
    program: "English  ",
    btn_1Link: "xyz375",
    btn_2Link: "abc33",
    btn_3Link: "qwe33",
    btn_4Link: "cvs378",
  },
  {
    id: "49",
    name: "logs",
    department: "VIII",
    program: "logs",
    btn_1Link: "xyz485",
    btn_2Link: "abc43",
    btn_3Link: "qwe43",
    btn_4Link: "cvs43",
  },
  {
    id: "50",
    name: "Physics++",
    department: "IV",
    program: "Physics++",
    btn_1Link: "xyz5",
    btn_2Link: "abc585378",
    btn_3Link: "qwe5738",
    btn_4Link: "cvs578638",
  },
  {
    id: "51",
    name: "Social Studies",
    department: "IV",
    program: "Social Studies",
    btn_1Link: "xyz6773878",
    btn_2Link: "abc683857",
    btn_3Link: "qwe68537",
    btn_4Link: "cvs763867",
  },
  {
    id: "52",
    name: "java++",
    department: "V",
    program: "java++",
    btn_1Link: "x853yz7",
    btn_2Link: "ab7c7",
    btn_3Link: "qw738e7",
    btn_4Link: "cv3s7",
  },
  {
    id: "53",
    name: "html5",
    department: "VI",
    program: "html5",
    btn_1Link: "xy78z8",
    btn_2Link: "ab78c8",
    btn_3Link: "qw7767e8",
    btn_4Link: "cv767s8",
  },
  {
    id: "54",
    name: "ux",
    department: "VII",
    program: "ux",
    btn_1Link: "x76yz9",
    btn_2Link: "a786bc9",
    btn_3Link: "qw76e9",
    btn_4Link: "c8v76s9",
  },
  {
    id: "55",
    name: "ui-ux",
    department: "VIII",
    program: "ui-ux",
    btn_1Link: "xyz7610",
    btn_2Link: "ab786c10",
    btn_3Link: "qw78e10",
    btn_4Link: "cvs7810",
  },
  {
    id: "56",
    name: "xd",
    department: " III",
    program: "xd",
    btn_1Link: "xy786z11",
    btn_2Link: "ab786c11",
    btn_3Link: "qw786e11",
    btn_4Link: "cv5868s11",
  },
  {
    id: "57",
    name: "mern",
    department: "II",
    program: "mern",
    btn_1Link: "xy86z12",
    btn_2Link: "ab786c12",
    btn_3Link: "qw786e12",
    btn_4Link: "cv786s12",
  },
  {
    id: "58",
    name: "c#",
    department: " IX",
    program: "c#",
    btn_1Link: "xy7868z13",
    btn_2Link: "ab76c13",
    btn_3Link: "qw786e13",
    btn_4Link: "cvs78613",
  },
  {
    id: "59",
    name: "geopolitics",
    department: "X",
    program: "geopolitics",
    btn_1Link: "xyz1471",
    btn_2Link: "abc143",
    btn_3Link: "qwe147828",
    btn_4Link: "cvs144",
  },
  {
    id: "60",
    name: "phthon",
    department: "VI",
    program: "phthon",
    btn_1Link: "xyz150",
    btn_2Link: "abc154",
    btn_3Link: "qwe1585",
    btn_4Link: "cvs157",
  },


  
];

export default CourseData;
